// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/ezio1119/fishapp-post/models"

import post_grpc "github.com/ezio1119/fishapp-post/post/controllers/post_grpc"
import time "time"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, p
func (_m *Usecase) Create(ctx context.Context, p *models.Post) (*post_grpc.Post, error) {
	ret := _m.Called(ctx, p)

	var r0 *post_grpc.Post
	if rf, ok := ret.Get(0).(func(context.Context, *models.Post) *post_grpc.Post); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post_grpc.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Post) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, userID
func (_m *Usecase) Delete(ctx context.Context, id int64, userID int64) error {
	ret := _m.Called(ctx, id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Usecase) GetByID(ctx context.Context, id int64) (*post_grpc.Post, error) {
	ret := _m.Called(ctx, id)

	var r0 *post_grpc.Post
	if rf, ok := ret.Get(0).(func(context.Context, int64) *post_grpc.Post); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post_grpc.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, datetime, num
func (_m *Usecase) GetList(ctx context.Context, datetime time.Time, num int64) (*post_grpc.ListPost, error) {
	ret := _m.Called(ctx, datetime, num)

	var r0 *post_grpc.ListPost
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int64) *post_grpc.ListPost); ok {
		r0 = rf(ctx, datetime, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post_grpc.ListPost)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int64) error); ok {
		r1 = rf(ctx, datetime, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, p, userID
func (_m *Usecase) Update(ctx context.Context, p *models.Post, userID int64) (*post_grpc.Post, error) {
	ret := _m.Called(ctx, p, userID)

	var r0 *post_grpc.Post
	if rf, ok := ret.Get(0).(func(context.Context, *models.Post, int64) *post_grpc.Post); ok {
		r0 = rf(ctx, p, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post_grpc.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Post, int64) error); ok {
		r1 = rf(ctx, p, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
