version: '3'
services:
  post-db:
    image: mysql:8.0.17
    volumes:
      - post-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: post_DB
      TZ: Asia/Tokyo
    ports:
      - "4306:3306"
  post:
    build:
      context: .
      dockerfile: Dockerfile.fresh
    volumes:
      - ./src/.:/app
    depends_on:
      - post-db
    tty: true
    environment:
      TZ: Asia/Tokyo
      DB_DBMS: mysql
      DB_PASS: password
      DB_NAME: post_DB
      DB_PORT: 3306
      DB_HOST: post-db
      DB_USER: root
      DB_CONN_OPT: charset=utf8mb4&parseTime=True&loc=Local
      TIMEOUT: 2
      LISTEN_PORT: 50051
      DEBUG: "true"
    ports:
      - "50051:50051"
      
  # grpcurl:
  #   image: networld/grpcurl
  #   command: /grpcurl -plaintext -d '{}' -H "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzczNDQ1NzEsImlzcyI6InJlZnJlc2hUb2tlbiIsInN1YiI6IjIzIn0.w0gAwAkMymK6iZxwjENP7AqsvEHgmLw3lqN2f6bWw1I" post:50051 post_grpc.PostService/Create
  #   tty: true
volumes:
  post-data:
    driver: local