version: '3.4'
services:
  post-db:
    image: mysql:8.0
    volumes:
      - post-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs --log-bin=postdb.bin --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: post_DB
      TZ: Asia/Tokyo　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
    ports:
      - "7306:3306"

  post:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    depends_on:
      - post-db
    environment:
      TZ: Asia/Tokyo

volumes:
  post-data:
  
networks:
  default:
    external:
      name: fishapp-net
