version: '3'
services:
  post-db:
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    volumes:
      - post-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=ON --general-log-file=/var/log/mysql/query.log
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: post_DB
      TZ: Asia/Tokyo
    ports:
      - "7306:3306"

  post:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    depends_on:
      - post-db
    tty: true
    environment:
      TZ: Asia/Tokyo

volumes:
  post-data:
    driver: local
networks:
  default:
    external:
      name: api-gateway_default
