// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/entry/controllers/entry_post_grpc/entry_post.proto

package entry_post_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               int64                `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c461d244bb10d73, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entry) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Entry) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Entry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Entry) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateReq struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c461d244bb10d73, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CreateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c461d244bb10d73, []int{2}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "entry_post_grpc.Entry")
	proto.RegisterType((*CreateReq)(nil), "entry_post_grpc.CreateReq")
	proto.RegisterType((*DeleteReq)(nil), "entry_post_grpc.DeleteReq")
}

func init() {
	proto.RegisterFile("src/entry/controllers/entry_post_grpc/entry_post.proto", fileDescriptor_4c461d244bb10d73)
}

var fileDescriptor_4c461d244bb10d73 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xb7, 0x75, 0x2c, 0x8a, 0x42, 0x0e, 0x6e, 0xf4, 0xa0, 0xa5, 0xa7, 0x9d, 0x5a,
	0x98, 0x20, 0x08, 0x1e, 0xdc, 0xfc, 0x01, 0x3b, 0x09, 0x53, 0xbc, 0x8e, 0xac, 0x79, 0x8e, 0x40,
	0xb6, 0xc4, 0x24, 0x9d, 0xf8, 0x4f, 0xf8, 0x2f, 0xf9, 0x7f, 0x79, 0x92, 0x24, 0xeb, 0x2a, 0x9d,
	0xb0, 0x5b, 0xdf, 0xfb, 0x7e, 0xdf, 0xeb, 0xe7, 0x7d, 0x83, 0xae, 0xb4, 0x2a, 0x72, 0x58, 0x1b,
	0xf5, 0x99, 0x17, 0x62, 0x6d, 0x94, 0xe0, 0x1c, 0x94, 0xf6, 0x9d, 0xb9, 0x14, 0xda, 0xcc, 0x97,
	0x4a, 0x16, 0x7f, 0xea, 0x4c, 0x2a, 0x61, 0x04, 0x3e, 0x6d, 0x38, 0xe2, 0xfe, 0x86, 0x70, 0x46,
	0x89, 0x81, 0xbc, 0xfa, 0xf0, 0xce, 0xf8, 0x62, 0x29, 0xc4, 0x92, 0x43, 0xee, 0xaa, 0x45, 0xf9,
	0x96, 0x1b, 0xb6, 0x02, 0x6d, 0xc8, 0x4a, 0x6e, 0x0d, 0xe7, 0x4d, 0xc3, 0x87, 0x22, 0x52, 0x82,
	0xd2, 0x5e, 0x4f, 0xbf, 0x03, 0xd4, 0x79, 0xb0, 0x7f, 0xc3, 0x27, 0x28, 0x64, 0x74, 0x10, 0x24,
	0xc1, 0xb0, 0x35, 0x0b, 0x19, 0xc5, 0x7d, 0xd4, 0x75, 0x00, 0x8c, 0x0e, 0x42, 0xd7, 0x8c, 0x6c,
	0x39, 0x75, 0x42, 0xa9, 0x41, 0x59, 0xa1, 0xe5, 0x05, 0x5b, 0x4e, 0x29, 0xbe, 0x46, 0xa8, 0x50,
	0x40, 0x0c, 0xd0, 0x39, 0x31, 0x83, 0x76, 0x12, 0x0c, 0x8f, 0x46, 0x71, 0xe6, 0x01, 0xb2, 0x0a,
	0x20, 0x7b, 0xa9, 0x08, 0x67, 0xbd, 0xad, 0x7b, 0x6c, 0xec, 0x68, 0x29, 0x69, 0x35, 0xda, 0x39,
	0x3c, 0xba, 0x75, 0x8f, 0x4d, 0xfa, 0x84, 0x7a, 0x77, 0x6e, 0xcf, 0x0c, 0xde, 0x71, 0x52, 0x43,
	0xbb, 0x4b, 0x26, 0xdd, 0x9f, 0x49, 0x3b, 0x0d, 0x87, 0xc1, 0x8e, 0x3e, 0xa9, 0xe9, 0xc3, 0x86,
	0xc3, 0x9f, 0x91, 0x3e, 0xa2, 0xde, 0x3d, 0x70, 0xf0, 0x0b, 0xfb, 0x75, 0x2a, 0xb5, 0xd3, 0xc6,
	0x73, 0x70, 0xcf, 0xe8, 0x2b, 0x40, 0xc7, 0x2e, 0xda, 0x67, 0x50, 0x1b, 0x56, 0x00, 0xbe, 0x41,
	0x91, 0x27, 0xc5, 0x71, 0xd6, 0x78, 0xe1, 0x6c, 0x77, 0x42, 0x7c, 0xb6, 0xa7, 0xf9, 0xf7, 0xb9,
	0x45, 0x91, 0xc7, 0xfa, 0x67, 0x7a, 0xc7, 0x1b, 0xef, 0x87, 0x36, 0x11, 0x82, 0xbf, 0x12, 0x5e,
	0xc2, 0x22, 0x72, 0xbd, 0xcb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x9b, 0xc1, 0x1f, 0x97,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntryServiceClient is the client API for EntryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntryServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Entry, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
}

type entryServiceClient struct {
	cc *grpc.ClientConn
}

func NewEntryServiceClient(cc *grpc.ClientConn) EntryServiceClient {
	return &entryServiceClient{cc}
}

func (c *entryServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Entry, error) {
	out := new(Entry)
	err := c.cc.Invoke(ctx, "/entry_post_grpc.EntryService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/entry_post_grpc.EntryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntryServiceServer is the server API for EntryService service.
type EntryServiceServer interface {
	Create(context.Context, *CreateReq) (*Entry, error)
	Delete(context.Context, *DeleteReq) (*wrappers.BoolValue, error)
}

// UnimplementedEntryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEntryServiceServer struct {
}

func (*UnimplementedEntryServiceServer) Create(ctx context.Context, req *CreateReq) (*Entry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEntryServiceServer) Delete(ctx context.Context, req *DeleteReq) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterEntryServiceServer(s *grpc.Server, srv EntryServiceServer) {
	s.RegisterService(&_EntryService_serviceDesc, srv)
}

func _EntryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entry_post_grpc.EntryService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entry_post_grpc.EntryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entry_post_grpc.EntryService",
	HandlerType: (*EntryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EntryService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EntryService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/entry/controllers/entry_post_grpc/entry_post.proto",
}
